version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
     - 27017:27017
    #mount volume to our file system
    volumes:
      - ./data/db:/data/db


  
  flask:
    # path to  Dockerfile
    build: ./backend
    # name of the container
    container_name: backend-flask
    # restart the service 
    restart: on-failure
    # mount volume for our Flask app
    volumes:
      - ./backend:/backend
    depends_on:
      -  mongodb
    # port mapping
    ports:
      - "5050:5050"
    command: python web.py